Repository RedHatInsights/tower-analytics-frontend, pull requests merged in 2020-11, with the labels that each got.

#321 Notifications Page UXD Audit Changes
  src/Components/NotificationsList.js
  src/Components/NotificationsList.test.js
  src/Containers/Notifications/Notifications.js
Labels: UXD, enhancement

#314 Automation Calculator UXD Audit
  src/Containers/AutomationCalculator/AutomationCalculator.js
Labels: UXD, enhancement, needs_test

#350 Toolbar fixes
  src/Components/Toolbar/Toolbar.js
  src/Containers/JobExplorer/JobExplorer.js
Labels: needs_test
