Repository RedHatInsights/tower-analytics-frontend, pull requests merged in 2020-06, with the labels that each got.

#148 Converting charts to functional components
  src/Charts/BarChart.js
  src/Charts/BaseChart.js
  src/Charts/GroupedBarChart.js
  src/Charts/LineChart.js
  src/Charts/PieChart.js
  src/Charts/tests/Chart.test.js
  src/Charts/tests/__snapshots__/Chart.test.js.snap
Labels: enhancement

#162 more sentence casing
  src/Charts/GroupedBarChart.js
  src/Charts/LineChart.js
  src/Charts/ROITopTemplates.js
  src/Components/TemplatesList.js
  src/Containers/AutomationCalculator/AutomationCalculator.js
  src/Utilities/Tooltip.js
Labels: needs_test

#168 Fixes padding issue on templates list and modules list
  src/App.scss
  src/Components/ModulesList.js
  src/Components/TemplatesList.js
Labels: bug
